# Generated by Django 4.0.4 on 2022-12-17 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DisLikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PageContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_logo', models.ImageField(blank=True, null=True, upload_to='page_contents/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='page_contents/')),
                ('footer_description', models.CharField(blank=True, max_length=200, null=True)),
                ('footer_address', models.CharField(blank=True, max_length=50, null=True)),
                ('footer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('footer_email', models.CharField(blank=True, max_length=50, null=True)),
                ('social_icon_1', models.CharField(blank=True, default='https://dummyimage.com/28x28', max_length=30, null=True)),
                ('social_icon_url_1', models.URLField(default='#')),
                ('social_icon_2', models.CharField(blank=True, default='https://dummyimage.com/28x28', max_length=30, null=True)),
                ('social_icon_url_2', models.URLField(default='#')),
                ('social_icon_3', models.CharField(blank=True, default='https://dummyimage.com/28x28', max_length=30, null=True)),
                ('social_icon_url_3', models.URLField(default='#')),
                ('social_icon_4', models.CharField(blank=True, default='https://dummyimage.com/28x28', max_length=30, null=True)),
                ('social_icon_url_4', models.URLField(default='#')),
                ('social_icon_5', models.CharField(blank=True, default='https://dummyimage.com/28x28', max_length=30, null=True)),
                ('social_icon_url_5', models.URLField(default='#')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='ViewsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
