# Generated by Django 4.0.4 on 2022-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pagecontents_social_icon_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_2',
            field=models.CharField(blank=True, default='facebook', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_3',
            field=models.CharField(blank=True, default='youtube', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_4',
            field=models.CharField(blank=True, default='pinterest', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_5',
            field=models.CharField(blank=True, default='instagram', max_length=30, null=True),
        ),
    ]
