# Generated by Django 4.0.4 on 2022-12-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagecontents_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_url_1',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_url_2',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_url_3',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_url_4',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_url_5',
            field=models.URLField(default='https://google.com'),
        ),
    ]
