# Generated by Django 4.0.4 on 2022-12-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagecontents_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontents',
            name='footer_social_icon_1',
            field=models.CharField(blank=True, default='facebook-f', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='footer_social_icon_2',
            field=models.CharField(blank=True, default='twitter', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='footer_social_icon_3',
            field=models.CharField(blank=True, default='instagram', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='footer_social_icon_4',
            field=models.CharField(blank=True, default='youtube', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='footer_social_icon_url_1',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='footer_social_icon_url_2',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='footer_social_icon_url_3',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='footer_social_icon_url_4',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AlterField(
            model_name='pagecontents',
            name='social_icon_4',
            field=models.CharField(blank=True, default='instagram', max_length=30, null=True),
        ),
    ]
