# Generated by Django 4.0.4 on 2022-12-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_channel_channel_subscription_dislike_like_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='datetime',
        ),
    ]
