# Generated by Django 4.0.4 on 2022-12-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_datetime_channel_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_image',
            field=models.ImageField(blank=True, default='https://dummyimage.com/1600x900', null=True, upload_to='channel_images/'),
        ),
    ]
