# Generated by Django 4.0.4 on 2022-12-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_channel_channel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='banner',
            field=models.ImageField(default='/static/1600x900.png', upload_to='video_banner'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
